#' Read Merlin LOD Score Table into Dataframe
#'
#' @param file
#'      .tbl file generated by Merlin
#' @param type
#'      either "parametric" or "nonparametric"
#' @return
#'      dataframe; columns vary by type argument
#' @export
readMerlinLodTable <- function(file,
                               type = c("parametric", "nonparametric")) {
    type <- match.arg(type)
    if(type == "parametric") {
        dat <- read.table(file = file, header = TRUE, sep = "\t", quote = "",
                          col.names = c("Chr", "Pos", "Label", "Model", "LOD",
                                        "Alpha", "HLOD"),
                          na.strings = "na", check.names = FALSE,
                          comment.char = "", stringsAsFactors = TRUE)
        dat$Pos <- dat$Pos * 100
    } else if(type == "nonparametric") {
        dat <- read.table(file = file, header = TRUE, sep = "\t", quote = "",
                          col.names = c("Chr", "Pos", "Label", "Analysis",
                                        "Zscore", "Delta", "LOD", "Pvalue",
                                        "ExDelta", "ExLOD", "ExPvalue"),
                          na.strings = "na", check.names = FALSE,
                          comment.char = "", stringsAsFactors = TRUE)
    } else {
        stop(sprintf("Invalid type argument: %s", type))
    }
    dat$Chr <- factor(dat$Chr)
    return(dat)
}
